version: '2'
services:
  web:
    image: fpfis/httpd-php:8.1-dev
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - ${PWD}:${PWD}
      - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      GITHUB_API_TOKEN:
      DOCUMENT_ROOT: ${PWD}/web
      XDEBUG_CONFIG: "remote_enable=1 remote_host=10.254.254.254 remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    networks:
      p2net:

  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      p2net:

  selenium:
    image: selenium/standalone-chrome:3.141.59
    environment:
      - DISPLAY=:99
    ports:
      - 5900:5900
    expose:
      - 4444
    networks:
      p2net:

volumes:
  mysql:

networks:
  p2net:
    driver: bridge
    ipam:
      driver: default
