name: Build
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  building:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.5.x', '10.0.x']
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          path: "."

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            mysql
            web
        env:
          PWD: "/home/p2-dev"

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Drupal core dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install

      - name: Install Drupal core dependencies in Web container
        run: |
          docker-compose exec -T web bash -c "composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install"

      - name: List files in Web container
        run: |
          docker-compose exec -T web bash -c "ls -lah web"

      - name: Build Dev Action
        run: |
          docker-compose exec -T web bash -c "./vendor/bin/run tk-bdev"

      - name: Install Drupal Action
        run: |
          docker-compose exec -T web bash -c "./vendor/bin/run tk-iclean"
