name: Test
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.5.x', '10.0.x']
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout Drupal core
        uses: actions/checkout@v2
        with:
          repository: drupal/drupal
          ref: ${{ matrix.drupal-core }}
          path: web/

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "{composer_cache_dir}={$(composer config cache-files-dir)}" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Drupal core dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install
      - name: Install module dependencies
        run: |
          composer --no-interaction --no-progress require \
            drupal/vartheme_bs5:^2.0@alpha
      - name: Install Coder module
        run: |
          composer --dev --no-interaction --no-progress require \
            drupal/coder:8.3.13
      - name: Check coding standards
        run: |
          ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
          ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js lib/
